import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'antd/dist/reset.css';
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";
import AntdProvider from "./providers/AntdProvider";

const geistSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-background text-foreground  antialiased`}
      >
        <AntdProvider>
          <Header />
          <main className="md:pt-18">

            {children}
          </main>
          <Footer />
        </AntdProvider>
      </body>
    </html>
  );
}
